/* MIRROR of `spec/config-shape.json` - design §4.3, verbatim.
 *
 * The JSON under `spec/` is the artifact every port reads; this module
 * is the TypeScript port's shipped copy of it. It exists because
 * `package.json` ships `dist/src` only, so a runtime read of `spec/`
 * works in the repo and breaks in a published consumer - and
 * `validateConfig` runs at `open()`, not just under test.
 *
 * DO NOT EDIT THIS FILE. Edit `spec/config-shape.json`, then re-run
 * `make sync-shape`. `test/shape.test.ts` fails on drift.
 */

export const CONFIG_SHAPE: any = {
  "station": [
    "`$EXACT`",
    1
  ],
  "profiles": {
    "`$CHILD`": {
      "secrets": {
        "providers": "`$LIST`"
      },
      "api": {
        "`$CHILD`": {
          "active": "`$BOOLEAN`",
          "package": [
            "`$ONE`",
            "`$NIL`",
            "`$STRING`"
          ],
          "export": [
            "`$ONE`",
            "`$NIL`",
            "`$STRING`"
          ],
          "base": [
            "`$ONE`",
            "`$NIL`",
            "`$STRING`"
          ],
          "secret": [
            "`$ONE`",
            "`$NIL`",
            "`$STRING`"
          ],
          "resolve": [
            "`$ONE`",
            "`$NIL`",
            [
              "`$EXACT`",
              "library"
            ],
            [
              "`$EXACT`",
              "proxy"
            ]
          ],
          "capture": [
            "`$ONE`",
            "`$NIL`",
            [
              "`$EXACT`",
              "meta"
            ],
            [
              "`$EXACT`",
              "headers"
            ],
            [
              "`$EXACT`",
              "full"
            ]
          ],
          "policy": [
            "`$ONE`",
            "`$NIL`",
            {
              "allow": [
                "`$ONE`",
                "`$NIL`",
                {
                  "method": [
                    "`$CHILD`",
                    "`$STRING`"
                  ],
                  "op": [
                    "`$CHILD`",
                    "`$STRING`"
                  ]
                }
              ],
              "budget": [
                "`$ONE`",
                "`$NIL`",
                {
                  "concurrency": [
                    "`$ONE`",
                    "`$NIL`",
                    "`$INTEGER`"
                  ],
                  "rps": [
                    "`$ONE`",
                    "`$NIL`",
                    "`$NUMBER`"
                  ]
                }
              ],
              "hosts": [
                "`$CHILD`",
                "`$STRING`"
              ],
              "mode": [
                "`$ONE`",
                "`$NIL`",
                [
                  "`$EXACT`",
                  "live"
                ],
                [
                  "`$EXACT`",
                  "record"
                ],
                [
                  "`$EXACT`",
                  "replay"
                ],
                [
                  "`$EXACT`",
                  "mock"
                ],
                [
                  "`$EXACT`",
                  "block"
                ]
              ]
            }
          ],
          "agent": [
            "`$ONE`",
            "`$NIL`",
            {
              "write": "`$BOOLEAN`"
            }
          ],
          "options": [
            "`$ONE`",
            "`$NIL`",
            "`$MAP`"
          ],
          "feature": {
            "`$CHILD`": {
              "active": "`$BOOLEAN`",
              "`$OPEN`": true
            }
          }
        }
      },
      "sdk": {
        "`$CHILD`": {
          "active": "`$BOOLEAN`",
          "package": [
            "`$ONE`",
            "`$NIL`",
            "`$STRING`"
          ],
          "export": [
            "`$ONE`",
            "`$NIL`",
            "`$STRING`"
          ],
          "base": [
            "`$ONE`",
            "`$NIL`",
            "`$STRING`"
          ],
          "secret": [
            "`$ONE`",
            "`$NIL`",
            "`$STRING`"
          ],
          "resolve": [
            "`$ONE`",
            "`$NIL`",
            [
              "`$EXACT`",
              "library"
            ],
            [
              "`$EXACT`",
              "proxy"
            ]
          ],
          "capture": [
            "`$ONE`",
            "`$NIL`",
            [
              "`$EXACT`",
              "meta"
            ],
            [
              "`$EXACT`",
              "headers"
            ],
            [
              "`$EXACT`",
              "full"
            ]
          ],
          "policy": [
            "`$ONE`",
            "`$NIL`",
            {
              "allow": [
                "`$ONE`",
                "`$NIL`",
                {
                  "method": [
                    "`$CHILD`",
                    "`$STRING`"
                  ],
                  "op": [
                    "`$CHILD`",
                    "`$STRING`"
                  ]
                }
              ],
              "budget": [
                "`$ONE`",
                "`$NIL`",
                {
                  "concurrency": [
                    "`$ONE`",
                    "`$NIL`",
                    "`$INTEGER`"
                  ],
                  "rps": [
                    "`$ONE`",
                    "`$NIL`",
                    "`$NUMBER`"
                  ]
                }
              ],
              "hosts": [
                "`$CHILD`",
                "`$STRING`"
              ],
              "mode": [
                "`$ONE`",
                "`$NIL`",
                [
                  "`$EXACT`",
                  "live"
                ],
                [
                  "`$EXACT`",
                  "record"
                ],
                [
                  "`$EXACT`",
                  "replay"
                ],
                [
                  "`$EXACT`",
                  "mock"
                ],
                [
                  "`$EXACT`",
                  "block"
                ]
              ]
            }
          ],
          "agent": [
            "`$ONE`",
            "`$NIL`",
            {
              "write": "`$BOOLEAN`"
            }
          ],
          "options": [
            "`$ONE`",
            "`$NIL`",
            "`$MAP`"
          ],
          "feature": {
            "`$CHILD`": {
              "active": "`$BOOLEAN`",
              "`$OPEN`": true
            }
          }
        }
      },
      "feature": {
        "`$CHILD`": {
          "active": "`$BOOLEAN`",
          "order": {
            "before": [
              "`$ONE`",
              "`$NIL`",
              "`$STRING`",
              [
                "`$CHILD`",
                "`$STRING`"
              ]
            ],
            "after": [
              "`$ONE`",
              "`$NIL`",
              "`$STRING`",
              [
                "`$CHILD`",
                "`$STRING`"
              ]
            ],
            "band": [
              "`$ONE`",
              "`$NIL`",
              "`$INTEGER`"
            ]
          },
          "`$OPEN`": true
        }
      }
    }
  }
}
