/* GENERATED FILE - DO NOT EDIT. Run `make sync-shape` (c/tools/sync-shape.py).
 *
 * The config grammar as data (design station.md 4.3), mirrored verbatim
 * from voxgig/station `spec/config-shape.json` - the one artifact every
 * port reads.
 *
 * A MIRROR rather than a run-time file read, because this library is
 * vendored into a generated C SDK and `vxstn_validate_config` runs at
 * open(), not only under test: there is no `spec/` beside the compiled
 * SDK to read. test/unit.c compares these bytes against the spec file
 * and fails on drift, which is what keeps a mirror honest.
 *
 * Line-per-line string literals, so a diff of this file reads like a
 * diff of the spec.
 */

#ifndef VOXGIG_STATION_CONFIG_SHAPE_H
#define VOXGIG_STATION_CONFIG_SHAPE_H

static const char VXSTN_CONFIG_SHAPE_JSON[] =
  "{\n"
  "  \"station\": [\n"
  "    \"`$EXACT`\",\n"
  "    1\n"
  "  ],\n"
  "  \"profiles\": {\n"
  "    \"`$CHILD`\": {\n"
  "      \"secrets\": {\n"
  "        \"providers\": \"`$LIST`\"\n"
  "      },\n"
  "      \"api\": {\n"
  "        \"`$CHILD`\": {\n"
  "          \"active\": \"`$BOOLEAN`\",\n"
  "          \"package\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            \"`$STRING`\"\n"
  "          ],\n"
  "          \"export\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            \"`$STRING`\"\n"
  "          ],\n"
  "          \"base\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            \"`$STRING`\"\n"
  "          ],\n"
  "          \"secret\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            \"`$STRING`\"\n"
  "          ],\n"
  "          \"resolve\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            [\n"
  "              \"`$EXACT`\",\n"
  "              \"library\"\n"
  "            ],\n"
  "            [\n"
  "              \"`$EXACT`\",\n"
  "              \"proxy\"\n"
  "            ]\n"
  "          ],\n"
  "          \"capture\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            [\n"
  "              \"`$EXACT`\",\n"
  "              \"meta\"\n"
  "            ],\n"
  "            [\n"
  "              \"`$EXACT`\",\n"
  "              \"headers\"\n"
  "            ],\n"
  "            [\n"
  "              \"`$EXACT`\",\n"
  "              \"full\"\n"
  "            ]\n"
  "          ],\n"
  "          \"policy\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            {\n"
  "              \"allow\": [\n"
  "                \"`$ONE`\",\n"
  "                \"`$NIL`\",\n"
  "                {\n"
  "                  \"method\": [\n"
  "                    \"`$CHILD`\",\n"
  "                    \"`$STRING`\"\n"
  "                  ],\n"
  "                  \"op\": [\n"
  "                    \"`$CHILD`\",\n"
  "                    \"`$STRING`\"\n"
  "                  ]\n"
  "                }\n"
  "              ],\n"
  "              \"budget\": [\n"
  "                \"`$ONE`\",\n"
  "                \"`$NIL`\",\n"
  "                {\n"
  "                  \"concurrency\": [\n"
  "                    \"`$ONE`\",\n"
  "                    \"`$NIL`\",\n"
  "                    \"`$INTEGER`\"\n"
  "                  ],\n"
  "                  \"rps\": [\n"
  "                    \"`$ONE`\",\n"
  "                    \"`$NIL`\",\n"
  "                    \"`$NUMBER`\"\n"
  "                  ]\n"
  "                }\n"
  "              ],\n"
  "              \"hosts\": [\n"
  "                \"`$CHILD`\",\n"
  "                \"`$STRING`\"\n"
  "              ],\n"
  "              \"mode\": [\n"
  "                \"`$ONE`\",\n"
  "                \"`$NIL`\",\n"
  "                [\n"
  "                  \"`$EXACT`\",\n"
  "                  \"live\"\n"
  "                ],\n"
  "                [\n"
  "                  \"`$EXACT`\",\n"
  "                  \"record\"\n"
  "                ],\n"
  "                [\n"
  "                  \"`$EXACT`\",\n"
  "                  \"replay\"\n"
  "                ],\n"
  "                [\n"
  "                  \"`$EXACT`\",\n"
  "                  \"mock\"\n"
  "                ],\n"
  "                [\n"
  "                  \"`$EXACT`\",\n"
  "                  \"block\"\n"
  "                ]\n"
  "              ]\n"
  "            }\n"
  "          ],\n"
  "          \"agent\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            {\n"
  "              \"write\": \"`$BOOLEAN`\"\n"
  "            }\n"
  "          ],\n"
  "          \"options\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            \"`$MAP`\"\n"
  "          ],\n"
  "          \"feature\": {\n"
  "            \"`$CHILD`\": {\n"
  "              \"active\": \"`$BOOLEAN`\",\n"
  "              \"`$OPEN`\": true\n"
  "            }\n"
  "          }\n"
  "        }\n"
  "      },\n"
  "      \"sdk\": {\n"
  "        \"`$CHILD`\": {\n"
  "          \"active\": \"`$BOOLEAN`\",\n"
  "          \"package\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            \"`$STRING`\"\n"
  "          ],\n"
  "          \"export\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            \"`$STRING`\"\n"
  "          ],\n"
  "          \"base\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            \"`$STRING`\"\n"
  "          ],\n"
  "          \"secret\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            \"`$STRING`\"\n"
  "          ],\n"
  "          \"resolve\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            [\n"
  "              \"`$EXACT`\",\n"
  "              \"library\"\n"
  "            ],\n"
  "            [\n"
  "              \"`$EXACT`\",\n"
  "              \"proxy\"\n"
  "            ]\n"
  "          ],\n"
  "          \"capture\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            [\n"
  "              \"`$EXACT`\",\n"
  "              \"meta\"\n"
  "            ],\n"
  "            [\n"
  "              \"`$EXACT`\",\n"
  "              \"headers\"\n"
  "            ],\n"
  "            [\n"
  "              \"`$EXACT`\",\n"
  "              \"full\"\n"
  "            ]\n"
  "          ],\n"
  "          \"policy\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            {\n"
  "              \"allow\": [\n"
  "                \"`$ONE`\",\n"
  "                \"`$NIL`\",\n"
  "                {\n"
  "                  \"method\": [\n"
  "                    \"`$CHILD`\",\n"
  "                    \"`$STRING`\"\n"
  "                  ],\n"
  "                  \"op\": [\n"
  "                    \"`$CHILD`\",\n"
  "                    \"`$STRING`\"\n"
  "                  ]\n"
  "                }\n"
  "              ],\n"
  "              \"budget\": [\n"
  "                \"`$ONE`\",\n"
  "                \"`$NIL`\",\n"
  "                {\n"
  "                  \"concurrency\": [\n"
  "                    \"`$ONE`\",\n"
  "                    \"`$NIL`\",\n"
  "                    \"`$INTEGER`\"\n"
  "                  ],\n"
  "                  \"rps\": [\n"
  "                    \"`$ONE`\",\n"
  "                    \"`$NIL`\",\n"
  "                    \"`$NUMBER`\"\n"
  "                  ]\n"
  "                }\n"
  "              ],\n"
  "              \"hosts\": [\n"
  "                \"`$CHILD`\",\n"
  "                \"`$STRING`\"\n"
  "              ],\n"
  "              \"mode\": [\n"
  "                \"`$ONE`\",\n"
  "                \"`$NIL`\",\n"
  "                [\n"
  "                  \"`$EXACT`\",\n"
  "                  \"live\"\n"
  "                ],\n"
  "                [\n"
  "                  \"`$EXACT`\",\n"
  "                  \"record\"\n"
  "                ],\n"
  "                [\n"
  "                  \"`$EXACT`\",\n"
  "                  \"replay\"\n"
  "                ],\n"
  "                [\n"
  "                  \"`$EXACT`\",\n"
  "                  \"mock\"\n"
  "                ],\n"
  "                [\n"
  "                  \"`$EXACT`\",\n"
  "                  \"block\"\n"
  "                ]\n"
  "              ]\n"
  "            }\n"
  "          ],\n"
  "          \"agent\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            {\n"
  "              \"write\": \"`$BOOLEAN`\"\n"
  "            }\n"
  "          ],\n"
  "          \"options\": [\n"
  "            \"`$ONE`\",\n"
  "            \"`$NIL`\",\n"
  "            \"`$MAP`\"\n"
  "          ],\n"
  "          \"feature\": {\n"
  "            \"`$CHILD`\": {\n"
  "              \"active\": \"`$BOOLEAN`\",\n"
  "              \"`$OPEN`\": true\n"
  "            }\n"
  "          }\n"
  "        }\n"
  "      },\n"
  "      \"feature\": {\n"
  "        \"`$CHILD`\": {\n"
  "          \"active\": \"`$BOOLEAN`\",\n"
  "          \"order\": {\n"
  "            \"before\": [\n"
  "              \"`$ONE`\",\n"
  "              \"`$NIL`\",\n"
  "              \"`$STRING`\",\n"
  "              [\n"
  "                \"`$CHILD`\",\n"
  "                \"`$STRING`\"\n"
  "              ]\n"
  "            ],\n"
  "            \"after\": [\n"
  "              \"`$ONE`\",\n"
  "              \"`$NIL`\",\n"
  "              \"`$STRING`\",\n"
  "              [\n"
  "                \"`$CHILD`\",\n"
  "                \"`$STRING`\"\n"
  "              ]\n"
  "            ],\n"
  "            \"band\": [\n"
  "              \"`$ONE`\",\n"
  "              \"`$NIL`\",\n"
  "              \"`$INTEGER`\"\n"
  "            ]\n"
  "          },\n"
  "          \"`$OPEN`\": true\n"
  "        }\n"
  "      }\n"
  "    }\n"
  "  }\n"
  "}\n";

#endif /* VOXGIG_STATION_CONFIG_SHAPE_H */
