#!/usr/bin/env python3
"""Mirror spec/config-shape.json into the TypeScript port's shipped copy.

package.json ships `dist/src` only, so a runtime read of `spec/` works in
the repo and breaks in a published consumer - and validateConfig runs at
open(), not just under test. test/shape.test.ts fails on drift.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'spec', 'config-shape.json')
OUT = os.path.join(ROOT, 'typescript', 'src', 'config-shape.ts')

HEADER = '''/* MIRROR of `spec/config-shape.json` - design §4.3, verbatim.
 *
 * The JSON under `spec/` is the artifact every port reads; this module
 * is the TypeScript port's shipped copy of it. It exists because
 * `package.json` ships `dist/src` only, so a runtime read of `spec/`
 * works in the repo and breaks in a published consumer - and
 * `validateConfig` runs at `open()`, not just under test.
 *
 * DO NOT EDIT THIS FILE. Edit `spec/config-shape.json`, then re-run
 * `make sync-shape`. `test/shape.test.ts` fails on drift.
 */

export const CONFIG_SHAPE: any = '''


def main() -> None:
    with open(SRC) as f:
        shape = json.load(f)
    with open(OUT, 'w') as f:
        f.write(HEADER + json.dumps(shape, indent=2) + '\n')
    print('sync-shape: wrote ' + os.path.relpath(OUT, ROOT))


if __name__ == '__main__':
    main()
