#!/usr/bin/env python3
"""Refresh, and check, the vendored payloads in sdkgen-station.

Four ports ship the station library INSIDE a generated SDK rather than
naming it as a dependency, because there is nothing to name: no Voxgig
distribution on CPAN, no LuaRocks rock, and no package registry at all
for c/cpp. Each payload's VENDORED.md states the contract - copies are
byte-identical to the canonical port, apart from the few transforms
recorded below.

The file list is GLOBBED from the canonical port, never hand-written.
That is the point: a file added to `c/src` or `perl/lib` and not carried
into the payload is drift too, and a hand-written manifest would not
notice it. `--check` fails on a missing file exactly as it fails on a
changed one.

Globbing canonical catches everything canonical HAS; it cannot, by
itself, catch what canonical has LOST. So the payload directories are
also reconciled the other way: a file sitting in a payload whose
canonical source was deleted or renamed is an ORPHAN, reported by
`--check` and deleted by `--write`. For c that is not housekeeping - the
generated SDK Makefile compiles `feature/*/*.c` by wildcard, so an
orphaned translation unit stays in the build, and a rename leaves the
same symbols defined twice.

    python3 tools/vendor.py --check    # CI: exit 1 on any drift
    python3 tools/vendor.py --write    # refresh the payloads

`c/src/config_shape.h` is generated by `c/tools/sync-shape.py` from
spec/config-shape.json. Run `make -C c sync-shape` before this if the
spec changed; this tool copies whatever is on disk and does not
regenerate it.
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TM = os.path.join(HERE, 'sdkgen-station', '.sdk', 'tm')


# --- the transforms -------------------------------------------------
#
# A transform is the ONLY sanctioned difference between a canonical file
# and its vendored copy. Each one is here because the vendored copy sits
# somewhere the canonical text cannot describe.

# perl: the header paragraph points the reader the other way round. The
# canonical says "edit HERE, then refresh the vendored copy"; the copy
# says "edit THERE first". Same information, opposite direction.
PERL_VENDORED_NOTE = """# NOTE ON COPIES: this is the VENDORED copy carried by the
# sdkgen-station package (.sdk/tm/perl/feature/station/lib/Voxgig/) and
# fanned out into generated Perl SDKs, which load everything by file
# path and cannot name a CPAN distribution (none exists for Voxgig).
# The CANONICAL source lives in the voxgig/station repo at
# perl/lib/Voxgig/ - edit THERE first, then refresh this copy; the two
# must stay byte-identical apart from this paragraph's counterpart.
# In a generated project, never edit at all: add is overwrite.
"""

PERL_NOTE_RE = re.compile(
    r'^# NOTE ON COPIES:.*?(?=^(?!#))', re.S | re.M)


def perl_note(text, _path):
    """Swap the canonical NOTE ON COPIES paragraph for the vendored one."""
    if '# NOTE ON COPIES:' not in text:
        return text
    return PERL_NOTE_RE.sub(PERL_VENDORED_NOTE, text, count=1)


# cpp: the canonical header includes struct as `"voxgig_struct.hpp"`
# and `"value_io.hpp"`, which resolve because the canonical build passes
# `-isystem <struct>/cpp/src`. A generated C++ SDK passes NO include
# flags at all - it is header-only and every include in it is relative -
# and its vendored struct lives at `utility/voxgigstruct/`
# (voxgig_struct.hpp, value.hpp, value_io.hpp). From `feature/station/`
# that is two levels up. Without this rewrite the payload does not
# compile in a generated SDK.
#
# Only the two headers station names itself are rewritten; struct's own
# `value.hpp`, which `voxgig_struct.hpp` includes, resolves relative to
# the including file and needs no help.
#
# c needs no counterpart: the generated C Makefile already carries
# `-I utility/struct` and compiles `feature/*/*.c` by wildcard, so the
# bare includes resolve and the new translation units are picked up.
CPP_STRUCT_DIR = '../../utility/voxgigstruct/'
CPP_STRUCT_HEADERS = ('voxgig_struct.hpp', 'value_io.hpp')

# The header that IS the library. It is the one file required to name
# both struct headers; see cpp_struct_include for why that distinction
# matters.
CPP_PRIMARY = 'voxgig_station.hpp'


def cpp_struct_include(text, path):
    # Rewrite whatever struct includes the file actually names - a helper
    # header added to `cpp/src` later has the same relative-path problem
    # if it names one, and none if it does not.
    #
    # The PRIMARY header is held to a stricter rule. A rewrite that
    # silently finds nothing there is the dangerous failure: it would
    # write a payload that looks refreshed and does not compile. So if
    # `voxgig_station.hpp` stops naming one of these, fail loudly and
    # make someone re-decide the rewrite.
    #
    # That strictness must NOT extend to other headers. Requiring every
    # globbed `.hpp` to name both would mean a newly added helper header
    # aborts the tool outright - breaking the very new-file guard the
    # glob exists to provide.
    primary = CPP_PRIMARY == os.path.basename(path)
    for header in CPP_STRUCT_HEADERS:
        want = '#include "%s"' % header
        if want not in text:
            if primary:
                raise SystemExit(
                    'vendor: %s no longer includes %s - the SDK include '
                    'rewrite is stale, fix CPP_STRUCT_HEADERS.'
                    % (CPP_PRIMARY, header))
            continue
        text = text.replace(want, '#include "%s%s"'
                            % (CPP_STRUCT_DIR, header))
    return text


def identity(text, _path):
    return text


# --- what is vendored where -----------------------------------------

def sekreto_home():
    for cand in [os.environ.get('SEKRETO_HOME'),
                 os.path.join(HERE, '..', 'sekreto'),
                 os.path.join(HERE, '..', '..', 'sekreto'),
                 '/workspace/sekreto', '/home/user/sekreto']:
        if cand and os.path.isfile(os.path.join(cand, 'spec', 'sekreto.json')):
            return os.path.abspath(cand)
    return None


def pairs():
    """(canonical, vendored, transform) for every vendored file.

    Globbed from the canonical side so a new canonical file shows up as
    drift rather than being silently left out of the payload.
    """
    out = []

    # perl: the station library ...
    perlsrc = os.path.join(HERE, 'perl', 'lib', 'Voxgig')
    perlfeat = os.path.join(TM, 'perl', 'feature', 'station')
    perldst = os.path.join(perlfeat, 'lib', 'Voxgig')
    for root, _dirs, files in os.walk(perlsrc):
        for name in sorted(files):
            if not name.endswith('.pm'):
                continue
            src = os.path.join(root, name)
            rel = os.path.relpath(src, perlsrc)
            out.append((src, os.path.join(perldst, rel), perl_note))

    # ... and its one dependency, from the sekreto checkout.
    home = sekreto_home()
    if home:
        seksrc = os.path.join(home, 'perl', 'lib', 'Voxgig')
        for root, _dirs, files in os.walk(seksrc):
            for name in sorted(files):
                if not name.endswith('.pm'):
                    continue
                src = os.path.join(root, name)
                rel = os.path.relpath(src, seksrc)
                out.append((src, os.path.join(perldst, rel), identity))

    # ... and the config shape, which the perl port reads from DISK at
    # open() rather than mirroring into code: Shape.pm walks up from its
    # own directory looking for `spec/config-shape.json` and dies if it
    # finds none, so a payload without this file is a generated SDK that
    # throws on the first open(). `feature/station/spec/` is four levels
    # up from `lib/Voxgig/Station/Shape.pm`, inside its eight-level walk.
    #
    # No other payload needs it: c compiles `config_shape.h` in, cpp
    # embeds the bytes in a generated function, and lua does not
    # validate against the shape at all.
    out.append((os.path.join(HERE, 'spec', 'config-shape.json'),
                os.path.join(perlfeat, 'spec', 'config-shape.json'),
                identity))

    # c: every source and header the library is built from.
    csrc = os.path.join(HERE, 'c', 'src')
    cdst = os.path.join(TM, 'c', 'feature', 'station')
    for name in sorted(os.listdir(csrc)):
        if name.endswith('.c') or name.endswith('.h'):
            out.append((os.path.join(csrc, name),
                        os.path.join(cdst, name), identity))

    # cpp: header-only.
    cppsrc = os.path.join(HERE, 'cpp', 'src')
    cppdst = os.path.join(TM, 'cpp', 'feature', 'station')
    for name in sorted(os.listdir(cppsrc)):
        if name.endswith('.hpp'):
            out.append((os.path.join(cppsrc, name),
                        os.path.join(cppdst, name), cpp_struct_include))

    # lua: one module.
    luasrc = os.path.join(HERE, 'lua', 'src')
    luadst = os.path.join(TM, 'lua', 'feature', 'station')
    for name in sorted(os.listdir(luasrc)):
        if name.endswith('.lua'):
            out.append((os.path.join(luasrc, name),
                        os.path.join(luadst, name), identity))

    return out


# --- what vendor.py owns, for orphan detection ----------------------

# The payload directories, whole. Everything under one of these is
# vendor.py's to write, EXCEPT the files named below - VENDORED.md is
# hand-written documentation that lives with the payload it describes.
#
# The sdkgen ADAPTER files (feature/station.c, feature/station.hpp,
# feature/station_feature.lua, feature/station_feature.pm) sit one level
# ABOVE these roots and so are outside them by construction. They are not
# vendor.py's and must never be touched.
MANAGED_ROOTS = ('perl', 'c', 'cpp', 'lua')

UNMANAGED = frozenset(['VENDORED.md'])


def owned():
    """Every file currently inside a payload directory that is ours.

    pairs() is driven by what canonical has NOW, so it can only ever
    notice a file that SHOULD be there. A canonical file that is deleted
    or renamed leaves its copy behind and no pair names it again - the
    copy goes stale invisibly, and `--check` keeps reporting success.

    For c that is not cosmetic: the generated SDK Makefile compiles
    `feature/*/*.c` by wildcard, so an orphaned translation unit stays in
    the build - and a RENAME leaves the same symbols defined twice.
    """
    out = []
    for lang in MANAGED_ROOTS:
        root = os.path.join(TM, lang, 'feature', 'station')
        if not os.path.isdir(root):
            continue
        for base, _dirs, files in os.walk(root):
            for name in files:
                if name in UNMANAGED:
                    continue
                out.append(os.path.join(base, name))
    return out


def expected(src, transform):
    with open(src, 'r', encoding='utf-8') as handle:
        return transform(handle.read(), src)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true',
                    help='report drift and exit 1; write nothing')
    ap.add_argument('--write', action='store_true',
                    help='refresh the payloads from canonical')
    args = ap.parse_args()
    if args.check == args.write:
        ap.error('pass exactly one of --check or --write')

    if not sekreto_home():
        print('vendor: voxgig/sekreto not found - set SEKRETO_HOME.',
              file=sys.stderr)
        print('vendor: the perl payload carries sekreto too, so a check '
              'without it would pass by looking at less.', file=sys.stderr)
        return 1

    drift = []
    wrote = 0
    removed = 0
    todo = pairs()
    keep = set(os.path.abspath(dst) for _src, dst, _t in todo)

    for src, dst, transform in todo:
        want = expected(src, transform)
        have = None
        if os.path.isfile(dst):
            with open(dst, 'r', encoding='utf-8') as handle:
                have = handle.read()

        if want == have:
            continue

        rel = os.path.relpath(dst, HERE)
        if args.check:
            drift.append((rel, 'missing' if have is None else 'differs',
                          os.path.relpath(src, HERE)))
        else:
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            with open(dst, 'w', encoding='utf-8') as handle:
                handle.write(want)
            wrote += 1
            print('%-8s %s' % ('created' if have is None else 'updated', rel))

    # Orphans: a payload file whose canonical source is gone. The loop
    # above cannot see these - it only walks what canonical HAS.
    for dst in sorted(owned()):
        if os.path.abspath(dst) in keep:
            continue
        rel = os.path.relpath(dst, HERE)
        if args.check:
            drift.append((rel, 'orphan', 'deleted from canonical'))
        else:
            os.remove(dst)
            removed += 1
            print('%-8s %s' % ('removed', rel))

    if args.write:
        print('vendor: %d file(s) refreshed, %d orphan(s) removed'
              % (wrote, removed))
        return 0

    if drift:
        print('vendor: %d vendored file(s) do not match canonical:'
              % len(drift), file=sys.stderr)
        for rel, why, src in drift:
            print('  %-8s %s  (canonical: %s)' % (why, rel, src),
                  file=sys.stderr)
        print('', file=sys.stderr)
        print('Edit the CANONICAL port, never the payload, then run:',
              file=sys.stderr)
        print('  make vendor-refresh', file=sys.stderr)
        return 1

    print('vendor: all payloads match canonical')
    return 0


if __name__ == '__main__':
    sys.exit(main())
